apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "swhp-operator.fullname" . }}
  labels:
    {{- include "swhp-operator.labels" . | nindent 4 }}
automountServiceAccountToken: true
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "swhp-operator.fullname" . }}
rules:
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["create", "delete"]
  - apiGroups: ["networking.k8s.io"]
    resources: ["ingresses"]
    verbs: ["create", "delete"]
  - apiGroups: ["apps"]
    resources: ["deployments", "statefulsets", "replicasets", "daemonsets"]
    verbs: ["patch", "list", "get"]
  - apiGroups: ["asterius.fr"]
    resources: ["staticchosts", "staticchost"]
    verbs: ["get", "list", "watch", "patch", "update"]
  - apiGroups: [""]
    resources: [events]
    verbs: [create]
  - apiGroups: ["apiextensions.k8s.io"]
    resources: ["customresourcedefinitions"]
    verbs: ["create"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "swhp-operator.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "swhp-operator.fullname" . }}
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ include "swhp-operator.fullname" . }}
  apiGroup: rbac.authorization.k8s.io
